/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Port7 */
#define Port7_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Port7_0_INBUF_ENABLED 0u
#define Port7_0_INIT_DRIVESTATE 0u
#define Port7_0_INIT_MUXSEL 0u
#define Port7_0_INPUT_SYNC 2u
#define Port7_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Port7_0_NUM 0u
#define Port7_0_PORT GPIO_PRT1
#define Port7_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Port7_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Port7_1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Port7_1_INBUF_ENABLED 0u
#define Port7_1_INIT_DRIVESTATE 0u
#define Port7_1_INIT_MUXSEL 0u
#define Port7_1_INPUT_SYNC 2u
#define Port7_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Port7_1_NUM 7u
#define Port7_1_PORT GPIO_PRT9
#define Port7_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Port7_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Port7_2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Port7_2_INBUF_ENABLED 0u
#define Port7_2_INIT_DRIVESTATE 0u
#define Port7_2_INIT_MUXSEL 0u
#define Port7_2_INPUT_SYNC 2u
#define Port7_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Port7_2_NUM 5u
#define Port7_2_PORT GPIO_PRT0
#define Port7_2_SLEWRATE CY_GPIO_SLEW_FAST
#define Port7_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Port7_3_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Port7_3_INBUF_ENABLED 0u
#define Port7_3_INIT_DRIVESTATE 0u
#define Port7_3_INIT_MUXSEL 0u
#define Port7_3_INPUT_SYNC 2u
#define Port7_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Port7_3_NUM 1u
#define Port7_3_PORT GPIO_PRT0
#define Port7_3_SLEWRATE CY_GPIO_SLEW_FAST
#define Port7_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Port7_4_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Port7_4_INBUF_ENABLED 0u
#define Port7_4_INIT_DRIVESTATE 0u
#define Port7_4_INIT_MUXSEL 0u
#define Port7_4_INPUT_SYNC 2u
#define Port7_4_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Port7_4_NUM 2u
#define Port7_4_PORT GPIO_PRT0
#define Port7_4_SLEWRATE CY_GPIO_SLEW_FAST
#define Port7_4_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Port7_5_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Port7_5_INBUF_ENABLED 0u
#define Port7_5_INIT_DRIVESTATE 0u
#define Port7_5_INIT_MUXSEL 0u
#define Port7_5_INPUT_SYNC 2u
#define Port7_5_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Port7_5_NUM 0u
#define Port7_5_PORT GPIO_PRT0
#define Port7_5_SLEWRATE CY_GPIO_SLEW_FAST
#define Port7_5_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Port7_6_DRIVEMODE CY_GPIO_DM_STRONG
#define Port7_6_INBUF_ENABLED 1u
#define Port7_6_INIT_DRIVESTATE 0u
#define Port7_6_INIT_MUXSEL 0u
#define Port7_6_INPUT_SYNC 2u
#define Port7_6_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Port7_6_NUM 0u
#define Port7_6_PORT GPIO_PRT6
#define Port7_6_SLEWRATE CY_GPIO_SLEW_FAST
#define Port7_6_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SW2_P0_4 */
#define SW2_P0_4_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define SW2_P0_4_0_INBUF_ENABLED 1u
#define SW2_P0_4_0_INIT_DRIVESTATE 1u
#define SW2_P0_4_0_INIT_MUXSEL 0u
#define SW2_P0_4_0_INPUT_SYNC 2u
#define SW2_P0_4_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SW2_P0_4_0_NUM 4u
#define SW2_P0_4_0_PORT GPIO_PRT0
#define SW2_P0_4_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SW2_P0_4_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SW2_P0_4_DRIVEMODE CY_GPIO_DM_PULLUP
#define SW2_P0_4_INBUF_ENABLED 1u
#define SW2_P0_4_INIT_DRIVESTATE 1u
#define SW2_P0_4_INIT_MUXSEL 0u
#define SW2_P0_4_INPUT_SYNC 2u
#define SW2_P0_4_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SW2_P0_4_NUM 4u
#define SW2_P0_4_PORT GPIO_PRT0
#define SW2_P0_4_SLEWRATE CY_GPIO_SLEW_FAST
#define SW2_P0_4_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_Red_P0_3 */
#define LED_Red_P0_3_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Red_P0_3_0_INBUF_ENABLED 0u
#define LED_Red_P0_3_0_INIT_DRIVESTATE 0u
#define LED_Red_P0_3_0_INIT_MUXSEL 0u
#define LED_Red_P0_3_0_INPUT_SYNC 2u
#define LED_Red_P0_3_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Red_P0_3_0_NUM 3u
#define LED_Red_P0_3_0_PORT GPIO_PRT0
#define LED_Red_P0_3_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Red_P0_3_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Red_P0_3_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Red_P0_3_INBUF_ENABLED 0u
#define LED_Red_P0_3_INIT_DRIVESTATE 0u
#define LED_Red_P0_3_INIT_MUXSEL 0u
#define LED_Red_P0_3_INPUT_SYNC 2u
#define LED_Red_P0_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Red_P0_3_NUM 3u
#define LED_Red_P0_3_PORT GPIO_PRT0
#define LED_Red_P0_3_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Red_P0_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_Blue_P11_1 */
#define LED_Blue_P11_1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Blue_P11_1_0_INBUF_ENABLED 0u
#define LED_Blue_P11_1_0_INIT_DRIVESTATE 0u
#define LED_Blue_P11_1_0_INIT_MUXSEL 0u
#define LED_Blue_P11_1_0_INPUT_SYNC 2u
#define LED_Blue_P11_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Blue_P11_1_0_NUM 1u
#define LED_Blue_P11_1_0_PORT GPIO_PRT11
#define LED_Blue_P11_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Blue_P11_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Blue_P11_1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Blue_P11_1_INBUF_ENABLED 0u
#define LED_Blue_P11_1_INIT_DRIVESTATE 0u
#define LED_Blue_P11_1_INIT_MUXSEL 0u
#define LED_Blue_P11_1_INPUT_SYNC 2u
#define LED_Blue_P11_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Blue_P11_1_NUM 1u
#define LED_Blue_P11_1_PORT GPIO_PRT11
#define LED_Blue_P11_1_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Blue_P11_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
