/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_Red */
#define Pin_Red_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Red_0_INBUF_ENABLED 0u
#define Pin_Red_0_INIT_DRIVESTATE 1u
#define Pin_Red_0_INIT_MUXSEL 3u
#define Pin_Red_0_INPUT_SYNC 2u
#define Pin_Red_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Red_0_NUM 3u
#define Pin_Red_0_PORT GPIO_PRT0
#define Pin_Red_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Red_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_Red_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Red_INBUF_ENABLED 0u
#define Pin_Red_INIT_DRIVESTATE 1u
#define Pin_Red_INIT_MUXSEL 3u
#define Pin_Red_INPUT_SYNC 2u
#define Pin_Red_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Red_NUM 3u
#define Pin_Red_PORT GPIO_PRT0
#define Pin_Red_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Red_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_Blue */
#define Pin_Blue_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Blue_0_INBUF_ENABLED 0u
#define Pin_Blue_0_INIT_DRIVESTATE 1u
#define Pin_Blue_0_INIT_MUXSEL 3u
#define Pin_Blue_0_INPUT_SYNC 2u
#define Pin_Blue_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Blue_0_NUM 1u
#define Pin_Blue_0_PORT GPIO_PRT11
#define Pin_Blue_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Blue_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_Blue_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Blue_INBUF_ENABLED 0u
#define Pin_Blue_INIT_DRIVESTATE 1u
#define Pin_Blue_INIT_MUXSEL 3u
#define Pin_Blue_INPUT_SYNC 2u
#define Pin_Blue_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Blue_NUM 1u
#define Pin_Blue_PORT GPIO_PRT11
#define Pin_Blue_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Blue_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_Green */
#define Pin_Green_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Green_0_INBUF_ENABLED 0u
#define Pin_Green_0_INIT_DRIVESTATE 1u
#define Pin_Green_0_INIT_MUXSEL 3u
#define Pin_Green_0_INPUT_SYNC 2u
#define Pin_Green_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Green_0_NUM 1u
#define Pin_Green_0_PORT GPIO_PRT1
#define Pin_Green_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Green_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_Green_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_Green_INBUF_ENABLED 0u
#define Pin_Green_INIT_DRIVESTATE 1u
#define Pin_Green_INIT_MUXSEL 3u
#define Pin_Green_INPUT_SYNC 2u
#define Pin_Green_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_Green_NUM 1u
#define Pin_Green_PORT GPIO_PRT1
#define Pin_Green_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Green_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
