/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* KIT_BTN1 */
#define KIT_BTN1_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define KIT_BTN1_0_INBUF_ENABLED 1u
#define KIT_BTN1_0_INIT_DRIVESTATE 1u
#define KIT_BTN1_0_INIT_MUXSEL 0u
#define KIT_BTN1_0_INPUT_SYNC 2u
#define KIT_BTN1_0_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define KIT_BTN1_0_NUM 4u
#define KIT_BTN1_0_PORT GPIO_PRT0
#define KIT_BTN1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define KIT_BTN1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define KIT_BTN1_DRIVEMODE CY_GPIO_DM_PULLUP
#define KIT_BTN1_INBUF_ENABLED 1u
#define KIT_BTN1_INIT_DRIVESTATE 1u
#define KIT_BTN1_INIT_MUXSEL 0u
#define KIT_BTN1_INPUT_SYNC 2u
#define KIT_BTN1_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define KIT_BTN1_NUM 4u
#define KIT_BTN1_PORT GPIO_PRT0
#define KIT_BTN1_SLEWRATE CY_GPIO_SLEW_FAST
#define KIT_BTN1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* KIT_LED_RED */
#define KIT_LED_RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define KIT_LED_RED_0_INBUF_ENABLED 0u
#define KIT_LED_RED_0_INIT_DRIVESTATE 0u
#define KIT_LED_RED_0_INIT_MUXSEL 0u
#define KIT_LED_RED_0_INPUT_SYNC 2u
#define KIT_LED_RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define KIT_LED_RED_0_NUM 7u
#define KIT_LED_RED_0_PORT GPIO_PRT13
#define KIT_LED_RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define KIT_LED_RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define KIT_LED_RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define KIT_LED_RED_INBUF_ENABLED 0u
#define KIT_LED_RED_INIT_DRIVESTATE 0u
#define KIT_LED_RED_INIT_MUXSEL 0u
#define KIT_LED_RED_INPUT_SYNC 2u
#define KIT_LED_RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define KIT_LED_RED_NUM 7u
#define KIT_LED_RED_PORT GPIO_PRT13
#define KIT_LED_RED_SLEWRATE CY_GPIO_SLEW_FAST
#define KIT_LED_RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* KIT_LED_BLUE */
#define KIT_LED_BLUE_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define KIT_LED_BLUE_0_INBUF_ENABLED 0u
#define KIT_LED_BLUE_0_INIT_DRIVESTATE 0u
#define KIT_LED_BLUE_0_INIT_MUXSEL 0u
#define KIT_LED_BLUE_0_INPUT_SYNC 2u
#define KIT_LED_BLUE_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define KIT_LED_BLUE_0_NUM 1u
#define KIT_LED_BLUE_0_PORT GPIO_PRT11
#define KIT_LED_BLUE_0_SLEWRATE CY_GPIO_SLEW_FAST
#define KIT_LED_BLUE_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define KIT_LED_BLUE_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define KIT_LED_BLUE_INBUF_ENABLED 0u
#define KIT_LED_BLUE_INIT_DRIVESTATE 0u
#define KIT_LED_BLUE_INIT_MUXSEL 0u
#define KIT_LED_BLUE_INPUT_SYNC 2u
#define KIT_LED_BLUE_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define KIT_LED_BLUE_NUM 1u
#define KIT_LED_BLUE_PORT GPIO_PRT11
#define KIT_LED_BLUE_SLEWRATE CY_GPIO_SLEW_FAST
#define KIT_LED_BLUE_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
