/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* isrTimer */
#define isrTimer__INTC_CORTEXM4_ASSIGNED 1
#define isrTimer__INTC_CORTEXM4_PRIORITY 7u
#define isrTimer__INTC_NUMBER 90u
#define isrTimer_INTC_CORTEXM4_ASSIGNED 1
#define isrTimer_INTC_CORTEXM4_PRIORITY 7u
#define isrTimer_INTC_NUMBER 90u

/* SysInt_Switch */
#define SysInt_Switch__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_Switch__INTC_CORTEXM4_PRIORITY 0u
#define SysInt_Switch__INTC_NUMBER 0u
#define SysInt_Switch_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_Switch_INTC_CORTEXM4_PRIORITY 0u
#define SysInt_Switch_INTC_NUMBER 0u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
