/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_Red */
#define LED_Red_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Red_0_INBUF_ENABLED 0u
#define LED_Red_0_INIT_DRIVESTATE 1u
#define LED_Red_0_INIT_MUXSEL 0u
#define LED_Red_0_INPUT_SYNC 2u
#define LED_Red_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Red_0_NUM 3u
#define LED_Red_0_PORT GPIO_PRT0
#define LED_Red_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Red_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Red_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Red_INBUF_ENABLED 0u
#define LED_Red_INIT_DRIVESTATE 1u
#define LED_Red_INIT_MUXSEL 0u
#define LED_Red_INPUT_SYNC 2u
#define LED_Red_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Red_NUM 3u
#define LED_Red_PORT GPIO_PRT0
#define LED_Red_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Red_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* KIT_BTN1 */
#define KIT_BTN1_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define KIT_BTN1_0_INBUF_ENABLED 1u
#define KIT_BTN1_0_INIT_DRIVESTATE 1u
#define KIT_BTN1_0_INIT_MUXSEL 0u
#define KIT_BTN1_0_INPUT_SYNC 2u
#define KIT_BTN1_0_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define KIT_BTN1_0_NUM 4u
#define KIT_BTN1_0_PORT GPIO_PRT0
#define KIT_BTN1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define KIT_BTN1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define KIT_BTN1_DRIVEMODE CY_GPIO_DM_PULLUP
#define KIT_BTN1_INBUF_ENABLED 1u
#define KIT_BTN1_INIT_DRIVESTATE 1u
#define KIT_BTN1_INIT_MUXSEL 0u
#define KIT_BTN1_INPUT_SYNC 2u
#define KIT_BTN1_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define KIT_BTN1_NUM 4u
#define KIT_BTN1_PORT GPIO_PRT0
#define KIT_BTN1_SLEWRATE CY_GPIO_SLEW_FAST
#define KIT_BTN1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_Blue */
#define LED_Blue_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Blue_0_INBUF_ENABLED 0u
#define LED_Blue_0_INIT_DRIVESTATE 1u
#define LED_Blue_0_INIT_MUXSEL 0u
#define LED_Blue_0_INPUT_SYNC 2u
#define LED_Blue_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Blue_0_NUM 1u
#define LED_Blue_0_PORT GPIO_PRT11
#define LED_Blue_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Blue_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Blue_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Blue_INBUF_ENABLED 0u
#define LED_Blue_INIT_DRIVESTATE 1u
#define LED_Blue_INIT_MUXSEL 0u
#define LED_Blue_INPUT_SYNC 2u
#define LED_Blue_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Blue_NUM 1u
#define LED_Blue_PORT GPIO_PRT11
#define LED_Blue_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Blue_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
